
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrabajoFinalWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleBoleta
{

    public int ID { get; set; }

    public int IdPedido { get; set; }

    public decimal MontoTotal { get; set; }

    public int IdModoDePago { get; set; }



    public virtual ModoDePago ModoDePago { get; set; }

    public virtual Pedido Pedido { get; set; }

}

}
