
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrabajoFinalWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empleado
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empleado()
    {

        this.Pedidoes = new HashSet<Pedido>();

    }


    public string ID { get; set; }

    public string Contraseña { get; set; }

    public int IdTipoEmpleado { get; set; }

    public string Nombre { get; set; }

    public int Celular { get; set; }

    public string Correo { get; set; }

    public string Direccion { get; set; }

    public decimal Sueldo { get; set; }



    public virtual TipoEmpleado TipoEmpleado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pedido> Pedidoes { get; set; }

}

}
