
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrabajoFinalWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PP
{

    public int ID { get; set; }

    public Nullable<int> IdProducto { get; set; }

    public Nullable<int> IdPedido { get; set; }

    public string Observacion { get; set; }



    public virtual Producto Producto { get; set; }

    public virtual P P { get; set; }

}

}
